---
#tasks file for firewall(ufw)
##included in common/main.yml

- name: "install firewall(ufw)"
  become: true
  apt: name={{item}} state=present
  with_items:
    - ufw

- name: "ufw allow ssh (always) !important"
  become: true
  ufw:
    rule: allow
    name: ssh
  notify: reload_ufw
  register: ufw_status
  ignore_errors: True

- name: "ufw allow ssh (always) !important"
  become: true
  ufw:
    rule: allow
    name: OpenSSH
  notify: reload_ufw
  register: ufw_status_openssh
  ignore_errors: True
  when: ufw_status is failed

  #if ufw fails wipe other rules in the iptables and try again
- name: try to fix ufw
  become: True
  command: "sudo ufw disable; sudo iptables -F; sudo iptables -X; sudo ip6tables -F; sudo ip6tables -X; sudo ufw allow ssh; sudo ufw enable"
  notify: reload_ufw
  when: (ufw_status is failed) and (ufw_status_openssh is failed)

- name: "try again: ufw allow ssh (always) !important"
  become: true
  ufw:
    rule: allow
    name: ssh
  notify: reload_ufw
  register: ufw_status_fallback
  when: (ufw_status is failed) and (ufw_status_openssh is failed)

- name: "try again: ufw allow ssh (always) !important"
  become: true
  ufw:
    rule: allow
    name: OpenSSH
  notify: reload_ufw
  register: ufw_status_openssh_fallback
  when: ufw_status_fallback is failed

- name: "copy ufw config before.rules"
  become: true
  copy:
    src: before.rules
    dest: /etc/ufw/before.rules
    owner: root
    group: root
    mode: 0644
    backup: no
  notify: reload_ufw

- name: update ufw default forward policy to ACCEPT (for vpn)
  become: true
  lineinfile:
    dest: /etc/default/ufw
    regexp: ^DEFAULT_FORWARD_POLICY
    line: DEFAULT_FORWARD_POLICY="ACCEPT"
  notify: reload_ufw

- name: "enable ufw"
  become: true
  ufw:
    state: enabled
  notify: reload_ufw
